# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73a52e7b2f726be8e512069d000162454d522a9853ad164d78c20544eca1878a9b11d85e4ee6743704231e0c3487beece4735f896938088fad8d13e392719bf9

test:
  secret_key_base: 8b1cbdecbad5764a80ea9fe2c38479b6ba855d065f154e28600da642e0469acd884e768078a146d54a2de7012f85ece0993015ad665fd5275d9056b81db841bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
